version: "3"

# All available services
services:

  # Computation
  jupyter:
    container_name: "Umoja_Hack_jupyter"
    restart: "always"
    build: services/jupyter
    env_file:
      - ./config/jupyter.env
      - ./config/shared_database.env
    volumes:
      - ./shared/:/home/jovyan/work/
    ports:
      - 8888:8888
    entrypoint: sh -c 'start-notebook.sh --NotebookApp.token=$$JUPYTER_PASSWORD'

  # Model Storage
  mlflow:
    container_name: "Umoja_Hack_mlflow"
    restart: "always"
    build: services/mlflow
    volumes:
      - ./shared/tracking:/tracking
      - ./shared/artifacts:/artifacts
    ports:
      - 5000:5000
    command:
        - "mlflow server"
        #- "--backend-store-uri ${MLFLOW_BACKEND_STORE}"
        - "--default-artifact-root /artifacts"
        - "--host 0.0.0.0"
        - "--port 5000"

  # Admin Overview
  portainer:
    container_name: "Umoja_Hack_portainer"
    restart: "always"
    image: portainer/portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_volume:/data
    ports:
      - 9090:9000
    command: -H unix:///var/run/docker.sock

# Volumes to persist data
volumes:
  mlflow_volume:
  portainer_volume:
